# runs native speed. Tar is 42mb seems worth it. 
# Release optimisation level = "s" makes it 38mb but drops performance by aroudn 20%.


# ---- Stage 1: Build ----
FROM docker.io/rust:1.87-slim AS builder

# Install required tools and create workdir
RUN apt-get update && apt-get install -y pkg-config libssl-dev

WORKDIR /app

# Copy actual source code
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock
COPY src src
COPY benches benches

RUN sed -i 's/ mma/ ci_mma/g' src/db.rs
RUN sed -i 's/\"mma\"/\"ci_mma\"/g' src/db.rs
RUN sed -i 's/127.0.0.1:9042/mmapod:9042/g' src/main.rs


# Build your actual project
RUN cargo build --release

RUN cp /app/target/release/mma /usr/local/bin/app

RUN echo "DEV_MODE=1" > /.env

RUN ls -lh /usr/local/bin/app
# ---- Stage 2: Runtime ----
FROM gcr.io/distroless/cc-debian12:nonroot 
# Or just cc-debian12 for root user

# Copy built binary from builder
COPY --from=builder /usr/local/bin/app /usr/local/bin/app
COPY templates templates
COPY schema schema
COPY auth auth
COPY --from=builder /.env /.env
# Or copy a pre-made .env file

EXPOSE 1227

CMD ["/usr/local/bin/app"]
