# 5.4MB docker image - + upx binary, opt ="z", release img is scratch
# ---- Stage 1: build + package ----
FROM docker.io/rust:1.87-alpine as builder

# Install build dependencies
RUN apk add --no-cache \
    musl-dev \
    build-base \
    curl \
    pkgconfig \
    perl \
    cmake \
    bash \
    coreutils \
    libgcc \
    libstdc++

# Set env to use vendored OpenSSL
ENV OPENSSL_STATIC=1
ENV OPENSSL_NO_VENDOR=0

WORKDIR /app

# Install UPX
RUN curl -L https://github.com/upx/upx/releases/download/v5.0.1/upx-5.0.1-amd64_linux.tar.xz | tar -xJ \
 && mv upx-5.0.1-amd64_linux/upx /usr/local/bin/ \
 && chmod +x /usr/local/bin/upx

COPY Cargo.toml Cargo.lock ./

# Configure static linking
RUN mkdir -p ./cargo && \
    printf '[target.x86_64-unknown-linux-musl]\nrustflags = ["-C", "target-feature=+crt-static"]\n' > ./cargo/config.toml
RUN rustup target add x86_64-unknown-linux-musl

# RUN mkdir src && echo 'fn main() { println!("Hello"); }' > ./src/main.rs
# RUN cargo build --release

COPY src/        src/
COPY benches/    benches/

# apply your sed patches…
RUN sed -i 's/ mma/ ci_mma/g' src/db.rs \
 && sed -i 's/"mma"/"ci_mma"/g' src/db.rs \
 && sed -i 's/127.0.0.1:9042/mmapod:9042/g' src/main.rs

RUN cargo build --release  --target x86_64-unknown-linux-musl
RUN strip target/x86_64-unknown-linux-musl/release/mma
RUN ls -lh target/x86_64-unknown-linux-musl/release/mma
RUN upx --lzma target/x86_64-unknown-linux-musl/release/mma
RUN ls -lh target/x86_64-unknown-linux-musl/release/mma


# package into a tar.gz
RUN cp /app/target/x86_64-unknown-linux-musl/release/mma /usr/local/bin/app

# capture ENV file
RUN echo "DEV_MODE=1" > /.env_runtime

# ---- Stage 2: runtime ----
FROM scratch
WORKDIR /app

# 2) copy your compressed payload + assets + .env
COPY --from=builder --chown=65532:65532 /usr/local/bin/app /app/mma
COPY --from=builder --chown=65532:65532 /.env_runtime     /app/.env
COPY --chown=65532:65532 templates         /app/templates
COPY --chown=65532:65532 schema            /app/schema
COPY --chown=65532:65532 auth              /app/auth

EXPOSE 1227

CMD ["/app/mma"]