FROM debian:bullseye-slim

# Install dependencies and hey
RUN apt-get update && \
    apt-get install -y curl unzip jq bc && \
    curl -L https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64 -o /usr/local/bin/hey && \
    chmod +x /usr/local/bin/hey 

# Default command (can be overridden)
ENTRYPOINT ["bash", "/external_bench.sh"]
